[v1]
"du-dust 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"grex 1.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"ripgrep 12.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"tealdeer 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"ytop 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["ytop"]
"zoxide 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
